### ISSUE TITLE
Stats are not displayed

### ISSUE THREAD

**Issue by yellowiscool** [shipyard/shipyard#675]
I just installed `shipyard/shipyard:latest` (where can I find the exact version?) and the container statistics are not displayed until I resize the browser window.

The javascript console has this error many times:
`Invalid value for <g> attribute transform="translate(NaN,5)"`

![shipyard](https://cloud.githubusercontent.com/assets/45740/11295240/a47bafec-8f72-11e5-924a-3b84a65fcedc.gif)

**Comment by ehazlett** [comment]
what version of docker

**Comment by baub** [comment]
Docker version 1.9.0, build 76d6bc9

**Comment by yellowiscool** [comment]
I have the same version.

**Comment by ehazlett** [comment]
Hmm what browser?

**Comment by yellowiscool** [comment]
I have this problem on both Firefox and Chrome.

**Comment by zzfzqq123** [comment]
the same problem~  Please answer！ thanks！

**Comment by pavankumarkatakam** [comment]
For me also same problem
Some use full info
### Docker Info
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

### Browsers
Chrome and Firefox
![console shipyard](https://cloud.githubusercontent.com/assets/6078669/11361143/25adaf2a-92b1-11e5-991a-16791a7d7f16.png)

**Comment by zzfzqq123** [comment]
Problem solved.
The reason：docker 1.9  stats  and shipyard  some incompatible。

The solution:

vim /static/app/containers/stats.controller.js
The modified content: 
addNetworkUsage(timestamp, node.networks.eth0.rx_bytes / 1048576, node.networks.eth0.tx_bytes / 1048576)

success!
done!

**Comment by John-Lin** [comment]
Docker 1.9 with docker remote API 1.21 has [a API changed](https://docs.docker.com/engine/reference/api/docker_remote_api/#v1-21-api-changes). 

> GET /containers/(id)/stats
> will return networking information respectively for each interface.

In the [`shipyard/controller/static/app/containers/stats.controller.js #L186`](https://github.com/shipyard/shipyard/blob/6aa1dbae965dc9f4ff73d58f51d92174435ccd12/controller/static/app/containers/stats.controller.js#L186) the second and third parameter should modify to:

`node.networks.<interface name>.rx_bytes` and `node.networks.<interface name>. tx_bytes `

**Comment by zittix** [comment]
This is fixed with my PR #688

**Comment by donmimo** [comment]
Not fixed yet, using the latest shipyard the stats are still broken even I see the changes made to /static/app/containers/stats.controller.js
